### ISSUE TITLE
MyoConnected event is not fired, when wakeing up a myo from sleep

### ISSUE THREAD

**Issue by neo9903** [tayfuzun/MyoSharp#3]
Can be reproduced by using the ConsoleSample:

1. Start the Sample
2. Wake up a Myo -> Myo Connected
3. Wait until Myo disconnects -> Myo Disconnects
4. Wake up Myo -> Myo should connect again, but it is not working

**Comment by ncosentino** [comment]
Thanks for the report. I'll try to reproduce this after work. In the
meantime, because this is open source, feel free to try to fix it on your
own and I'll gladly integrate the patch.

**Comment by neo9903** [comment]
I've found the problem.

In the latest version a Myo is added on pairing and removed on disconnect, but it should be removed at unpair.  Many Connects and Disconnects can happen between pair and unpair (Myo Standby,...).
-->
UnhookMyoEvents and removing the Myo should be moved from Myo_Disconnected to a new DeviceListener_Unpaired function.

**Comment by ncosentino** [comment]
Real life has been crazy. Sorry. I'll try to get this in tonight. Thanks for diving deeper on it.

**Comment by ncosentino** [comment]
I have the fix wired up now. Will commit shortly.

**Comment by ncosentino** [comment]
@neo9903 would you care to try out https://github.com/tayfuzun/MyoSharp/commit/2c40d0d764ce001e4c9d7463e3ac198059c54e3d to see if this fixes your issue?

**Comment by neo9903** [comment]
Hi,

Sorry for the late response, i was not able to reply earlier.

The bug is fixed now and works perfectly.

Thank you.

**Comment by ncosentino** [comment]
@neo9903 Thanks for all of your feedback! Glad I was able to get that resolved for you.
