### ISSUE TITLE
Specify requirements

### ISSUE THREAD

**Issue by timorzadir** [tayfuzun/MyoSharp#4]
This project requires `Microsoft Code Contracts`, but does not specify it anywhere. 
Please add it to the docs.

**Comment by ncosentino** [comment]
You got it, boss. Were you able to get up and running with it or are you
still stuck getting it to compile?

**Comment by timorzadir** [comment]
It compiled fine when i installed ´Microsoft Code Contracts` :)

**Comment by ncosentino** [comment]
@timorzadir I updated the front page. Let me know if there's anything else you'd like me to add specifically, and I'll try to include it.

**Comment by timorzadir** [comment]
Looks great :+1:
