### ISSUE TITLE
Error with Contracts reference

### ISSUE THREAD

**Issue by welshtom** [tayfuzun/MyoSharp#6]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Contracts' does not exist in the namespace 'System.Diagnostics' (are you missing an assembly reference?)	MyoSharp	\Documents\MyoSharp\MyoSharp\Commands\IMyoCommandResult.cs	3	Active

The project fails to build with the above error?

**Comment by welshtom** [comment]
my bad, didnt install the contracts plugin !

**Comment by ncosentino** [comment]
Hey!

Glad you figured it out :) I'm not sure why our github readme looks all
messed up... I'll look into it.
